const state = {
  modoRealTime: false,
  tendenciaSeleccionada: null,
  actualizarTendenciaHistoricas: false,
  variablesTendenciaHistoricas: null,
  variablesTendenciaTimpoReal: null,
  actualizarTv1Grafico: false,
  loadingTv1Grafico: true,
  variablesTv1Historicas: null,
  variablesTv1TiempoReal: null,
  actualizarTv2Grafico: false,
  loadingTv2Grafico: true,
  variablesTv2Historicas: null,
  variablesTv2TiempoReal: null,
  loadingTv3Grafico: true,
  actualizarTv3Grafico: false,
  variablesTv3Historicas: null,
  variablesTv3TiempoReal: null,
  loadingTv4Grafico: true,
  actualizarTv4Grafico: false,
  variablesTv4Historicas: null,
  variablesTv4TiempoReal: null,
  loadingTv5Grafico: true,
  actualizarTv5Grafico: false,
  variablesTv5Historicas: null,
  variablesTv5TiempoReal: null,
  loadingTv6Grafico: true,
  actualizarTv6Grafico: false,
  variablesTv6Historicas: null,
  variablesTv6TiempoReal: null
}

export default state
