#! /bin/sh
command touch .env
cat > .env << EOF
HOST= $HOST
PORT= $PORT
NODE_ENV= $NODE_ENV
APP_NAME= $APP_NAME
APP_URL= http://${HOST}:${PORT}
APP_KEY= $APP_KEY
DB_CONNECTION= $DB_CONNECTION
DB_USER= $DB_USER
DB_PASSWORD= $DB_PASSWORD
DB_DATABASE= $DB_DATABASE
DB_CONNECTION_WINCC= $DB_CONNECTION_WINCC
DB_HOST_WINCC= $DB_HOST_WINCC
DB_PORT_WINCC= $DB_PORT_WINCC
DB_USER_WINCC= $DB_USER_WINCC
DB_PASSWORD_WINCC= $DB_PASSWORD_WINCC
DB_DATABASE_WINCC= $DB_DATABASE_WINCC
HASH_DRIVER= $HASH_DRIVER
MAIL_CONNECTION= $MAIL_CONNECTION
SMTP_HOST= $SMTP_HOST
MAIL_USERNAME= $MAIL_USERNAME
MAIL_PASSWORD= $MAIL_PASSWORD
EOF